export interface City {
  id: string;
  name: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
}

export const CITIES: City[] = [
  { id: "nyc", name: "New York", country: "USA", latitude: 40.7128, longitude: -74.0060, timezone: "America/New_York" },
  { id: "la", name: "Los Angeles", country: "USA", latitude: 34.0522, longitude: -118.2437, timezone: "America/Los_Angeles" },
  { id: "chicago", name: "Chicago", country: "USA", latitude: 41.8781, longitude: -87.6298, timezone: "America/Chicago" },
  { id: "houston", name: "Houston", country: "USA", latitude: 29.7604, longitude: -95.3698, timezone: "America/Chicago" },
  { id: "miami", name: "Miami", country: "USA", latitude: 25.7617, longitude: -80.1918, timezone: "America/New_York" },
  { id: "sf", name: "San Francisco", country: "USA", latitude: 37.7749, longitude: -122.4194, timezone: "America/Los_Angeles" },
  { id: "seattle", name: "Seattle", country: "USA", latitude: 47.6062, longitude: -122.3321, timezone: "America/Los_Angeles" },
  { id: "boston", name: "Boston", country: "USA", latitude: 42.3601, longitude: -71.0589, timezone: "America/New_York" },
  { id: "denver", name: "Denver", country: "USA", latitude: 39.7392, longitude: -104.9903, timezone: "America/Denver" },
  { id: "london", name: "London", country: "UK", latitude: 51.5074, longitude: -0.1278, timezone: "Europe/London" },
  { id: "paris", name: "Paris", country: "France", latitude: 48.8566, longitude: 2.3522, timezone: "Europe/Paris" },
  { id: "berlin", name: "Berlin", country: "Germany", latitude: 52.5200, longitude: 13.4050, timezone: "Europe/Berlin" },
  { id: "madrid", name: "Madrid", country: "Spain", latitude: 40.4168, longitude: -3.7038, timezone: "Europe/Madrid" },
  { id: "rome", name: "Rome", country: "Italy", latitude: 41.9028, longitude: 12.4964, timezone: "Europe/Rome" },
  { id: "amsterdam", name: "Amsterdam", country: "Netherlands", latitude: 52.3676, longitude: 4.9041, timezone: "Europe/Amsterdam" },
  { id: "tokyo", name: "Tokyo", country: "Japan", latitude: 35.6762, longitude: 139.6503, timezone: "Asia/Tokyo" },
  { id: "beijing", name: "Beijing", country: "China", latitude: 39.9042, longitude: 116.4074, timezone: "Asia/Shanghai" },
  { id: "shanghai", name: "Shanghai", country: "China", latitude: 31.2304, longitude: 121.4737, timezone: "Asia/Shanghai" },
  { id: "seoul", name: "Seoul", country: "South Korea", latitude: 37.5665, longitude: 126.9780, timezone: "Asia/Seoul" },
  { id: "singapore", name: "Singapore", country: "Singapore", latitude: 1.3521, longitude: 103.8198, timezone: "Asia/Singapore" },
  { id: "dubai", name: "Dubai", country: "UAE", latitude: 25.2048, longitude: 55.2708, timezone: "Asia/Dubai" },
  { id: "sydney", name: "Sydney", country: "Australia", latitude: -33.8688, longitude: 151.2093, timezone: "Australia/Sydney" },
  { id: "melbourne", name: "Melbourne", country: "Australia", latitude: -37.8136, longitude: 144.9631, timezone: "Australia/Melbourne" },
  { id: "toronto", name: "Toronto", country: "Canada", latitude: 43.6532, longitude: -79.3832, timezone: "America/Toronto" },
  { id: "vancouver", name: "Vancouver", country: "Canada", latitude: 49.2827, longitude: -123.1207, timezone: "America/Vancouver" },
  { id: "mexico", name: "Mexico City", country: "Mexico", latitude: 19.4326, longitude: -99.1332, timezone: "America/Mexico_City" },
  { id: "sao_paulo", name: "São Paulo", country: "Brazil", latitude: -23.5505, longitude: -46.6333, timezone: "America/Sao_Paulo" },
  { id: "rio", name: "Rio de Janeiro", country: "Brazil", latitude: -22.9068, longitude: -43.1729, timezone: "America/Sao_Paulo" },
  { id: "buenos_aires", name: "Buenos Aires", country: "Argentina", latitude: -34.6037, longitude: -58.3816, timezone: "America/Argentina/Buenos_Aires" },
  { id: "moscow", name: "Moscow", country: "Russia", latitude: 55.7558, longitude: 37.6173, timezone: "Europe/Moscow" },
  { id: "istanbul", name: "Istanbul", country: "Turkey", latitude: 41.0082, longitude: 28.9784, timezone: "Europe/Istanbul" },
  { id: "cairo", name: "Cairo", country: "Egypt", latitude: 30.0444, longitude: 31.2357, timezone: "Africa/Cairo" },
  { id: "mumbai", name: "Mumbai", country: "India", latitude: 19.0760, longitude: 72.8777, timezone: "Asia/Kolkata" },
  { id: "delhi", name: "Delhi", country: "India", latitude: 28.7041, longitude: 77.1025, timezone: "Asia/Kolkata" },
  { id: "bangkok", name: "Bangkok", country: "Thailand", latitude: 13.7563, longitude: 100.5018, timezone: "Asia/Bangkok" },
  { id: "hong_kong", name: "Hong Kong", country: "China", latitude: 22.3193, longitude: 114.1694, timezone: "Asia/Hong_Kong" },
  { id: "barcelona", name: "Barcelona", country: "Spain", latitude: 41.3851, longitude: 2.1734, timezone: "Europe/Madrid" },
  { id: "lisbon", name: "Lisbon", country: "Portugal", latitude: 38.7223, longitude: -9.1393, timezone: "Europe/Lisbon" },
  { id: "vienna", name: "Vienna", country: "Austria", latitude: 48.2082, longitude: 16.3738, timezone: "Europe/Vienna" },
  { id: "prague", name: "Prague", country: "Czech Republic", latitude: 50.0755, longitude: 14.4378, timezone: "Europe/Prague" },
  { id: "stockholm", name: "Stockholm", country: "Sweden", latitude: 59.3293, longitude: 18.0686, timezone: "Europe/Stockholm" },
  { id: "copenhagen", name: "Copenhagen", country: "Denmark", latitude: 55.6761, longitude: 12.5683, timezone: "Europe/Copenhagen" },
  { id: "zurich", name: "Zurich", country: "Switzerland", latitude: 47.3769, longitude: 8.5417, timezone: "Europe/Zurich" },
  { id: "athens", name: "Athens", country: "Greece", latitude: 37.9838, longitude: 23.7275, timezone: "Europe/Athens" },
  { id: "oslo", name: "Oslo", country: "Norway", latitude: 59.9139, longitude: 10.7522, timezone: "Europe/Oslo" },
  { id: "helsinki", name: "Helsinki", country: "Finland", latitude: 60.1699, longitude: 24.9384, timezone: "Europe/Helsinki" },
  { id: "dublin", name: "Dublin", country: "Ireland", latitude: 53.3498, longitude: -6.2603, timezone: "Europe/Dublin" },
  { id: "brussels", name: "Brussels", country: "Belgium", latitude: 50.8503, longitude: 4.3517, timezone: "Europe/Brussels" },
  { id: "warsaw", name: "Warsaw", country: "Poland", latitude: 52.2297, longitude: 21.0122, timezone: "Europe/Warsaw" },
  { id: "budapest", name: "Budapest", country: "Hungary", latitude: 47.4979, longitude: 19.0402, timezone: "Europe/Budapest" },
  { id: "auckland", name: "Auckland", country: "New Zealand", latitude: -36.8485, longitude: 174.7633, timezone: "Pacific/Auckland" },
  { id: "cape_town", name: "Cape Town", country: "South Africa", latitude: -33.9249, longitude: 18.4241, timezone: "Africa/Johannesburg" },
  { id: "lagos", name: "Lagos", country: "Nigeria", latitude: 6.5244, longitude: 3.3792, timezone: "Africa/Lagos" },
  { id: "nairobi", name: "Nairobi", country: "Kenya", latitude: -1.2864, longitude: 36.8172, timezone: "Africa/Nairobi" },
];
